import crypto from "node:crypto";
import http from "node:http";
import { URL, URLSearchParams } from "node:url";
import type { RpConfig } from "./config.js";
import { logCallback, logJwksFetch, logLanding, type CallbackOutcome } from "./demolog.js";
import { renderCallbackPage, renderErrorPage, renderLandingPage } from "./html.js";
import { JwksClient, JwksFetchError, JwksKeyNotFoundError, type Jwk } from "./jwks.js";
import { decodeJwt, verifyIdToken, type DecodedJwt, type JwtPayload } from "./jwt.js";

/** Upper bound on a `/callback` form body. An id_token is a few hundred bytes. */
const MAX_BODY_BYTES = 1e6;

/** Thrown by `readUrlEncodedBody` when the body exceeds `MAX_BODY_BYTES`. */
class BodyTooLargeError extends Error {
  constructor() {
    super("Request body too large");
    this.name = "BodyTooLargeError";
  }
}

export interface CreateServerOptions extends RpConfig {
  /** Injectable JWKS client; one is built from `idpInternalUrl` when omitted. */
  jwksClient?: JwksClient;
  /** Injectable fetch, forwarded to the default JWKS client (tests). */
  fetchImpl?: typeof fetch;
}

/**
 * Reads an `application/x-www-form-urlencoded` body into a flat record.
 *
 * Chunks are collected as bytes and decoded once at the end: decoding each chunk
 * on its own would corrupt any multi-byte UTF-8 sequence that straddles a chunk
 * boundary. The size cap is therefore counted in bytes, not in code units.
 *
 * Past the cap the collected bytes are released and the rest of the body is
 * drained rather than retained, so memory stays bounded while the client can
 * still finish its upload and read the 413 instead of seeing a dropped
 * connection.
 */
function readUrlEncodedBody(req: http.IncomingMessage): Promise<Record<string, string>> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let size = 0;
    let tooLarge = false;

    req.on("data", (chunk: Buffer) => {
      if (tooLarge) return;
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        tooLarge = true;
        chunks.length = 0;
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (tooLarge) {
        reject(new BodyTooLargeError());
        return;
      }
      // fromEntries defines own properties, so a "__proto__" field in the body
      // stays an ordinary key instead of touching the object's prototype.
      resolve(Object.fromEntries(new URLSearchParams(Buffer.concat(chunks).toString("utf8"))));
    });
    req.on("error", reject);
  });
}

function sendHtml(res: http.ServerResponse, status: number, html: string): void {
  res.writeHead(status, {
    "Content-Type": "text/html; charset=utf-8",
    "Cache-Control": "no-store",
  });
  res.end(html);
}

function randomToken(): string {
  return crypto.randomBytes(16).toString("base64url");
}

/**
 * Builds the `/authorize` URL the login button points at.
 *
 * `nonce`/`state` are generated by the caller (not in here) so the demo log
 * can report the exact values that ended up in the URL.
 */
export function buildAuthorizeUrl(config: RpConfig, nonce: string, state: string): string {
  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: `${config.rpBaseUrl}/callback`,
    response_type: "id_token",
    response_mode: "form_post",
    scope: "openid profile email",
    nonce,
    state,
  });
  // URLSearchParams encodes spaces as "+"; OIDC authorize URLs conventionally use
  // %20, and the gateway's reference URL does too, so normalise the scope separator.
  return `${config.issuer}/authorize?${params.toString().replace(/\+/g, "%20")}`;
}

/**
 * Builds the RP HTTP server. Nothing is bound until `listen` is called, so tests
 * can start it on port 0.
 */
export function createRpServer(options: CreateServerOptions): http.Server {
  const config: RpConfig = {
    rpBaseUrl: options.rpBaseUrl,
    issuer: options.issuer,
    idpInternalUrl: options.idpInternalUrl,
    clientId: options.clientId,
  };
  const jwks =
    options.jwksClient ??
    new JwksClient({
      idpBaseUrl: config.idpInternalUrl,
      fetchImpl: options.fetchImpl,
      onFetch: logJwksFetch,
    });

  return http.createServer(async (req, res) => {
    try {
      const method = req.method ?? "GET";
      const pathname = new URL(req.url ?? "/", "http://localhost").pathname;

      if (method === "GET" && pathname === "/health") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ status: "ok" }));
        return;
      }

      if (method === "GET" && pathname === "/") {
        const nonce = randomToken();
        const state = randomToken();
        logLanding({ nonce, state });
        sendHtml(res, 200, renderLandingPage({ authorizeUrl: buildAuthorizeUrl(config, nonce, state) }));
        return;
      }

      if (method === "POST" && pathname === "/callback") {
        await handleCallback(req, res, config, jwks);
        return;
      }

      res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
      res.end("Not Found");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Internal server error";
      console.error("[RP] server error:", err);
      if (!res.headersSent) {
        sendHtml(res, 500, renderErrorPage(500, "Internal Server Error", message));
      } else {
        res.end();
      }
    }
  });
}

async function handleCallback(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  config: RpConfig,
  jwks: JwksClient
): Promise<void> {
  let formParams: Record<string, string>;
  try {
    formParams = await readUrlEncodedBody(req);
  } catch (err) {
    if (err instanceof BodyTooLargeError) {
      sendHtml(
        res,
        413,
        renderErrorPage(
          413,
          "Payload Too Large",
          `The form_post body exceeds the ${MAX_BODY_BYTES}-byte limit.`
        )
      );
      return;
    }
    throw err;
  }

  const idToken = formParams.id_token;
  const state = formParams.state;

  if (!idToken) {
    sendHtml(
      res,
      400,
      renderErrorPage(400, "Bad Request", "Missing id_token in the form_post body.")
    );
    return;
  }

  /** Renders the "認証失敗" page. `payload` is shown when the token parsed. */
  const rejectToken = (error: string, payload: JwtPayload | null): void => {
    sendHtml(
      res,
      401,
      renderCallbackPage({ valid: false, error, payload, issuer: config.issuer, state })
    );
  };

  const logOutcome = (outcome: CallbackOutcome): void =>
    logCallback({ idToken, state, idpInternalUrl: config.idpInternalUrl, outcome });

  // 1. Parse. A malformed token is a verification failure, not a server error.
  let decoded: DecodedJwt;
  try {
    decoded = decodeJwt(idToken);
  } catch (err) {
    const message = err instanceof Error ? err.message : "malformed token";
    logOutcome({ kind: "parse_failed", reason: message });
    rejectToken(message, null);
    return;
  }

  const kid = decoded.header.kid;

  // 2. Resolve the signing key by kid. Only an unreachable JWKS is a 502.
  let jwk: Jwk;
  try {
    jwk = await jwks.getSigningKey(kid);
  } catch (err) {
    if (err instanceof JwksFetchError) {
      logOutcome({ kind: "jwks_unreachable", kid, reason: err.message });
      sendHtml(
        res,
        502,
        renderErrorPage(
          502,
          "Bad Gateway",
          `IdP の JWKS (${jwks.uri}) を取得できませんでした: ${err.message}`
        )
      );
      return;
    }
    const message =
      err instanceof JwksKeyNotFoundError ? err.message : "failed to resolve the signing key";
    logOutcome({ kind: "verification_failed", kid, reason: message });
    rejectToken(message, decoded.payload);
    return;
  }

  // 3. Signature + claims.
  const result = verifyIdToken(decoded, jwk, { issuer: config.issuer, clientId: config.clientId });
  if (!result.valid) {
    const message = result.error ?? "verification failed";
    logOutcome({ kind: "verification_failed", kid, reason: message });
    rejectToken(message, decoded.payload);
    return;
  }

  const payload = decoded.payload;
  const aud = Array.isArray(payload.aud) ? payload.aud.join(",") : String(payload.aud);
  const expRemainingSeconds = Math.max(0, Math.floor((payload.exp ?? 0) - Date.now() / 1000));
  logOutcome({
    kind: "verified",
    kid: kid ?? "?",
    iss: String(payload.iss),
    aud,
    expRemainingSeconds,
    sub: String(payload.sub),
  });
  sendHtml(res, 200, renderCallbackPage({ valid: true, payload, issuer: config.issuer, state }));
}
