import crypto from "node:crypto";
import http from "node:http";
import { URL, URLSearchParams } from "node:url";
import type { RpConfig } from "./config.js";
import { logCallback, logCallbackRejected, logLanding } from "./demolog.js";
import {
  renderCallbackErrorPage,
  renderCallbackPage,
  renderErrorPage,
  renderLandingPage,
} from "./html.js";

export type CreateServerOptions = RpConfig;

function sendHtml(res: http.ServerResponse, status: number, html: string): void {
  res.writeHead(status, {
    "Content-Type": "text/html; charset=utf-8",
    "Cache-Control": "no-store",
  });
  res.end(html);
}

/** 128 random bits, base64url. Used for `state`. */
function randomToken(): string {
  return crypto.randomBytes(16).toString("base64url");
}

/** The one `redirect_uri` this client uses, at `/authorize` and again at `/token`. */
export function redirectUriFor(config: RpConfig): string {
  return `${config.rpBaseUrl}/callback`;
}

/**
 * Builds the `/authorize` URL the login button points at (contract section 14.1 step 2).
 *
 * `response_type=code`: the browser comes back to `/callback` with an authorization code
 * and exchanges it itself. `dpop_jkt` is not here — the inline script appends it once it
 * has read the key out of IndexedDB, because the server never learns the thumbprint.
 *
 * `openid` stays in `scope` even though this is OAuth rather than OIDC: the gateway's
 * `/authorize` still validates the scope the way it did for the OIDC flow, and dropping
 * the value would be a change to a component this project does not own.
 *
 * `state` is generated by the caller (not in here) so the demo log can report the exact
 * value that ended up in the URL.
 */
export function buildAuthorizeUrl(config: RpConfig, state: string): string {
  const params = new URLSearchParams({
    response_type: "code",
    client_id: config.clientId,
    redirect_uri: redirectUriFor(config),
    scope: "openid profile email",
    state,
  });
  // URLSearchParams encodes spaces as "+"; authorize URLs conventionally use %20, and the
  // gateway's reference URL does too, so normalise the scope separator.
  return `${config.issuer}/authorize?${params.toString().replace(/\+/g, "%20")}`;
}

/**
 * Builds the RP HTTP server. Nothing is bound until `listen` is called, so tests
 * can start it on port 0.
 *
 * Three GET routes and no state: since the OAuth step the server never calls the
 * authorization server, never holds a key, and never sees a token.
 */
export function createRpServer(options: CreateServerOptions): http.Server {
  const config: RpConfig = {
    rpBaseUrl: options.rpBaseUrl,
    issuer: options.issuer,
    clientId: options.clientId,
  };

  return http.createServer((req, res) => {
    try {
      const method = req.method ?? "GET";
      const url = new URL(req.url ?? "/", "http://localhost");
      const pathname = url.pathname;

      if (method === "GET" && pathname === "/health") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ status: "ok" }));
        return;
      }

      if (method === "GET" && pathname === "/") {
        const state = randomToken();
        logLanding({ state });
        sendHtml(
          res,
          200,
          renderLandingPage({ authorizeUrl: buildAuthorizeUrl(config, state), state })
        );
        return;
      }

      if (method === "GET" && pathname === "/callback") {
        handleCallback(res, config, url.searchParams);
        return;
      }

      res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
      res.end("Not Found");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Internal server error";
      console.error("[RP] server error:", err);
      if (!res.headersSent) {
        sendHtml(res, 500, renderErrorPage(500, "Internal Server Error", message));
      } else {
        res.end();
      }
    }
  });
}

/**
 * `GET /callback?code&state` — hand the browser the page that finishes the flow.
 *
 * Deliberately no `/token` call here. The code can only be spent together with a DPoP
 * proof, the proof can only be made with the key in the browser's IndexedDB, and the
 * `state` can only be compared against the browser's sessionStorage. All three belong to
 * the page, so the server's whole job is to escape the two query parameters into `data-`
 * attributes.
 *
 * `code` is the authentication assertion itself (contract section 14, revised): a
 * group-signed JWT, several hundred bytes of `xxx.yyy.zzz`, not an opaque handle. It is
 * passed through byte for byte — no truncation, no parsing, no interpretation. The rp
 * neither verifies it (it holds no group public key) nor needs to: the gateway and the
 * nodes check it at `/token`.
 */
function handleCallback(
  res: http.ServerResponse,
  config: RpConfig,
  query: URLSearchParams
): void {
  const error = query.get("error");
  const state = query.get("state") ?? "";
  const code = query.get("code");

  // RFC 6749 4.1.2.1: an error redirect carries no code, so it is checked first.
  if (error) {
    const description = query.get("error_description") ?? undefined;
    logCallbackRejected(
      `authorization server returned error=${error}${description ? ` (${description})` : ""}`
    );
    sendHtml(
      res,
      400,
      renderCallbackErrorPage({
        error,
        errorDescription: description,
        state: state || undefined,
        issuer: config.issuer,
      })
    );
    return;
  }

  if (!code) {
    logCallbackRejected("no code in the redirect query string");
    sendHtml(
      res,
      400,
      renderErrorPage(
        400,
        "Bad Request",
        "認可コード (アサーション JWT) がクエリにありません。/ からやり直してください。"
      )
    );
    return;
  }

  logCallback({ code, state: state || undefined });
  sendHtml(
    res,
    200,
    renderCallbackPage({
      code,
      state,
      issuer: config.issuer,
      clientId: config.clientId,
      redirectUri: redirectUriFor(config),
    })
  );
}
