import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { DEFAULT_KEY_ID, GroupFile, NodeFile } from "../src/dealer.js";
import { checkDealerOutput, hOf, recomputeH, toprfShareOf } from "./verify.js";
import { bytesToHex } from "../src/hex.js";
import { deriveServerKey } from "../src/crypto/toprf.js";

/**
 * `sample-output/` is committed as the fixture source for the node and gateway
 * test suites (docs/container-split.md section 4). It is not regenerated by the
 * tests, so it is verified here with exactly the checks a fresh run gets: a
 * corrupted or hand-edited fixture fails the dealer's own suite.
 */
const sampleDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "sample-output"
);

/** The passwords the committed fixtures were generated from. */
const SAMPLE_USERS = [
  { username: "alice", password: "password123", sub: "usr_alice_12345" },
  { username: "bob", password: "password456", sub: "usr_bob_67890" },
];

function readJson<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(sampleDir, name), "utf8")) as T;
}

describe("sample-output fixtures", () => {
  const group = readJson<GroupFile>("group.json");
  const nodes = [1, 2, 3].map((id) => readJson<NodeFile>(`node-${id}.json`));

  it("was generated with the default parameters", () => {
    expect(group.threshold).toBe(2);
    expect(group.total).toBe(3);
    expect(group.keyId).toBe(DEFAULT_KEY_ID);
  });

  it("satisfies every check a fresh dealer run must satisfy", () => {
    checkDealerOutput(group, nodes, SAMPLE_USERS);
  });

  it("detects a tampered fixture", () => {
    const tampered = nodes.map((n) => structuredClone(n));
    tampered[0].secretKeyShare = tampered[1].secretKeyShare;
    expect(() => checkDealerOutput(group, tampered, SAMPLE_USERS)).toThrow();
  });

  it("does not accept a wrong password against the fixtures", () => {
    const shares = [
      toprfShareOf(nodes[0], "alice"),
      toprfShareOf(nodes[1], "alice"),
    ];
    const h = recomputeH("not-alices-password", shares);
    expect(bytesToHex(deriveServerKey(h, 1))).not.toBe(hOf(nodes[0], "alice"));
  });
});
